"""Feature catalog — the authoritative 122-feature map (features 1-122).

Every row ties a feature to its REAL implementation (modules), the REAL
registered tools that expose it, its terminal entrypoints, offline posture,
risk, persistence/recovery/artifact behavior and dependencies. Availability is
computed live from the registry (see ``feature_status``) — a feature with no
tools is a framework feature whose terminal path is the natural-language ask.

The catalog is data, not a registry: the registry remains the single source of
truth for tool identity. ``verify_all_122.py`` reconciles this catalog against
the live registry.
"""

# Feature id -> row. ``tools`` names must EXIST in the registry
# (reconciled by verify_all_111). ``entrypoints`` are the real terminal paths.
FEATURES = [
    {"id": 1, "name": "AI Brain / Reasoning",
     "modules": ["brain/brain.py"], "tools": [],
     "entrypoints": ["cli --ask", "app.py --text"], "offline": "partial",
     "risk": "low", "dependency": "model provider (ollama or configured)",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 2, "name": "Boss Identity & Personality",
     "modules": ["core/identity.py", "config/defaults.py"],
     "tools": ["boss_facts", "boss_consult", "boss_set_preference"],
     "entrypoints": ["cli --ask 'what are boss preferences?'"],
     "offline": True, "risk": "low", "dependency": "none (local)",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 3, "name": "Long-Term Memory",
     "modules": ["memory/database.py", "memory/manager.py"],
     "tools": ["memory_store", "memory_search", "list_memories"],
     "entrypoints": ["cli --ask 'remember X'", "cli --ask 'search memory for Y'"],
     "offline": True, "risk": "low", "dependency": "sqlite (local)",
     "persistence": True, "recovery": "db-backed", "artifacts": "data/arven_memory.db"},
    {"id": 4, "name": "Natural Conversation",
     "modules": ["brain/brain.py", "core/conversation.py"], "tools": [],
     "entrypoints": ["cli --repl", "cli --ask"],
     "offline": "partial", "risk": "low", "dependency": "model provider",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 5, "name": "Agent System",
     "modules": ["brain/astra_agent.py", "core/background.py"], "tools": [],
     "entrypoints": ["cli --repl", "cli --ask"],
     "offline": "partial", "risk": "low", "dependency": "model provider",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 6, "name": "Computer Control",
     "modules": ["core/action_engine.py", "tools/apps.py"],
     "tools": ["open_app", "media_command", "action_execute"],
     "entrypoints": ["cli --ask 'open notepad'"],
     "offline": True, "risk": "medium", "dependency": "local OS",
     "persistence": False, "recovery": "guard/undo", "artifacts": "n/a"},
    {"id": 7, "name": "System Control",
     "modules": ["tools/system.py"],
     "tools": ["system_info", "running_processes", "run_shell", "date_time", "wifi_status"],
     "entrypoints": ["cli --ask 'system info'", "cli --ask 'run command X'"],
     "offline": True, "risk": "high", "dependency": "local OS",
     "persistence": False, "recovery": "guard", "artifacts": "n/a"},
    {"id": 8, "name": "File Management",
     "modules": ["tools/files.py"],
     "tools": ["create_file", "read_file", "write_file", "append_to_file",
               "list_files", "search_files", "delete_file", "delete_folder"],
     "entrypoints": ["cli --ask 'create file X'", "cli --ask 'list files'"],
     "offline": True, "risk": "medium", "dependency": "local FS",
     "persistence": True, "recovery": "undo", "artifacts": "files"},
    {"id": 9, "name": "Document Intelligence",
     "modules": ["tools/documents.py"],
     "tools": ["list_documents", "read_document"],
     "entrypoints": ["cli --ask 'read the document'"],
     "offline": True, "risk": "low", "dependency": "local files",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 10, "name": "RAG / Knowledge Retrieval",
     "modules": ["memory/rag.py", "memory/retrieval.py"],
     "tools": ["memory_search", "list_memories"],
     "entrypoints": ["cli --ask 'search knowledge for X'"],
     "offline": "partial", "risk": "low", "dependency": "embeddings (local)",
     "persistence": True, "recovery": "db-backed", "artifacts": "data/rag_index.json"},
    {"id": 11, "name": "Web Search",
     "modules": ["tools/web.py"],
     "tools": ["web_search", "fetch_page", "browser_search"],
     "entrypoints": ["cli --ask 'search the web for X'"],
     "offline": False, "risk": "low", "dependency": "network",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 12, "name": "Research Agent",
     "modules": ["brain/astra_agent.py"],
     "tools": ["web_search", "fetch_page"],
     "entrypoints": ["cli --ask 'research X and compare the sources'"],
     "offline": False, "risk": "low", "dependency": "network + model provider",
     "persistence": False, "recovery": "n/a", "artifacts": "reports"},
    {"id": 13, "name": "Computer Use Framework",
     "modules": ["brain/computer_use_agent.py"],
     "tools": ["open_app", "media_command", "action_execute"],
     "entrypoints": ["cli --ask", "cli --ask 'interact with the computer'"],
     "offline": True, "risk": "medium", "dependency": "local OS",
     "persistence": False, "recovery": "guard", "artifacts": "screenshots"},
    {"id": 14, "name": "Coding Agent",
     "modules": ["brain/coding_agent.py"], "tools": ["build_validate", "qa_pytest"],
     "entrypoints": ["cli --ask 'write code for X'"],
     "offline": "partial", "risk": "medium", "dependency": "model provider",
     "persistence": False, "recovery": "n/a", "artifacts": "code files"},
    {"id": 15, "name": "Voice Input / STT",
     "modules": ["voice/input.py"], "tools": [],
     "entrypoints": ["verify_stt.py"],
     "offline": True, "risk": "low", "dependency": "faster-whisper + mic",
     "persistence": False, "recovery": "n/a", "artifacts": "Logs/*.wav"},
    {"id": 16, "name": "Voice Output / TTS",
     "modules": ["voice/output.py", "tools/tts_tools.py"],
     "tools": ["tts_speak", "tts_speak_clean", "tts_status"],
     "entrypoints": ["cli --ask 'say hello'"],
     "offline": True, "risk": "low", "dependency": "Windows SAPI",
     "persistence": False, "recovery": "n/a", "artifacts": "Logs/*.wav"},
    {"id": 17, "name": "Wake Word",
     "modules": ["voice/wakeword.py"], "tools": [],
     "entrypoints": ["app.py --hotkey-agent"],
     "offline": True, "risk": "low", "dependency": "mic",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 18, "name": "Scheduler / Reminders",
     "modules": ["core/scheduler.py", "core/organizer.py"],
     "tools": ["organizer_reminder_create", "organizer_reminders", "organizer_daily_plan"],
     "entrypoints": ["cli --ask 'remind me at 5pm'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/organizer.json"},
    {"id": 19, "name": "Background Agents",
     "modules": ["core/background.py"], "tools": [],
     "entrypoints": ["cli --ask", "cli --repl"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "worker isolation", "artifacts": "n/a"},
    {"id": 20, "name": "Proactive Assistant",
     "modules": ["core/proactive.py", "tools/proactive_tools.py"],
     "tools": ["proactive_status", "proactive_suggest"],
     "entrypoints": ["cli --ask 'proactive status'"],
     "offline": True, "risk": "low", "dependency": "local + scheduler",
     "persistence": True, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 21, "name": "Media Control",
     "modules": ["tools/media.py"],
     "tools": ["media_command", "media_command_phrase", "media_status"],
     "entrypoints": ["cli --ask 'media status'"],
     "offline": True, "risk": "low", "dependency": "pycaw/comtypes (if volume)",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 22, "name": "Plugin / Skill System",
     "modules": ["core/skill_builder.py"],
     "tools": ["skill_define", "skill_invoke", "skill_list", "skill_verify"],
     "entrypoints": ["cli --ask 'list skills'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "skills/"},
    {"id": 23, "name": "Tool Registry",
     "modules": ["tools/registry.py", "tools/builder.py"],
     "tools": ["capability_probe", "feature_status"],
     "entrypoints": ["cli --features", "cli --feature <id>"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 24, "name": "Security & Permissions",
     "modules": ["core/security.py", "core/access.py"],
     "tools": ["access_grant", "access_check", "access_revoke", "access_report",
               "guardian_permission_review", "guardian_policy"],
     "entrypoints": ["cli --ask 'access report'"],
     "offline": True, "risk": "high", "dependency": "local",
     "persistence": True, "recovery": "audit", "artifacts": "data/access.json"},
    {"id": 25, "name": "Error Recovery",
     "modules": ["core/recovery.py", "core/undo.py"], "tools": [],
     "entrypoints": ["cli --repl"], "offline": True, "risk": "low",
     "dependency": "local", "persistence": True, "recovery": "guard+undo",
     "artifacts": "data/undo.json"},
    {"id": 26, "name": "Health Monitor",
     "modules": ["core/health.py"],
     "tools": ["health_rollup", "diagnostics_run"],
     "entrypoints": ["cli --health"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 27, "name": "Offline Mode",
     "modules": ["core/capabilities.py", "core/capability_awareness.py"],
     "tools": ["capability_probe", "capability_graph"],
     "entrypoints": ["cli --capabilities"],
     "offline": True, "risk": "low", "dependency": "local probes",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 28, "name": "Logging & Diagnostics",
     "modules": ["core/logging.py"],
     "tools": ["diagnostics_run", "diagnostics_report"],
     "entrypoints": ["cli --health", "Logs/arven.log"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "n/a", "artifacts": "Logs/arven.log"},
    {"id": 29, "name": "Performance / Lifecycle",
     "modules": ["core/performance.py", "core/lifecycle.py"],
     "tools": ["perf_report", "perf_benchmark", "perf_hotspots"],
     "entrypoints": ["cli --ask 'performance report'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 30, "name": "Context References",
     "modules": ["core/reference.py"],
     "tools": ["context_query", "context_summary", "context_focus", "context_event_push"],
     "entrypoints": ["cli --ask 'what is the current context?'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/context.json"},
    {"id": 31, "name": "Clarification Engine",
     "modules": ["core/clarification.py"], "tools": [],
     "entrypoints": ["cli --ask (ambiguous)"], "offline": True, "risk": "low",
     "dependency": "local", "persistence": False, "recovery": "n/a",
     "artifacts": "n/a"},
    {"id": 32, "name": "Confirmation / Trust System",
     "modules": ["core/confirmation.py"], "tools": ["escalate"],
     "entrypoints": ["cli --approve", "cli --answer RID:yes"],
     "offline": True, "risk": "high", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 33, "name": "Multimodal Input Framework",
     "modules": ["core/multimodal.py"],
     "tools": ["multimodal_ingest", "multimodal_recent"],
     "entrypoints": ["cli --ask 'ingest image X'"],
     "offline": True, "risk": "medium", "dependency": "local files",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/multimodal.json"},
    {"id": 34, "name": "Output Management",
     "modules": ["core/output.py"],
     "tools": ["report_export"],
     "entrypoints": ["cli --ask 'save report'"],
     "offline": True, "risk": "low", "dependency": "local FS",
     "persistence": True, "recovery": "n/a", "artifacts": "Output/, Logs/"},
    {"id": 35, "name": "Self-Test / Test System",
     "modules": ["core/selftest.py", "core/qa_engine.py"],
     "tools": ["run_selftest", "qa_syntax", "qa_imports", "qa_pytest"],
     "entrypoints": ["cli --ask 'run self test'"],
     "offline": True, "risk": "low", "dependency": "pytest (for qa_pytest)",
     "persistence": False, "recovery": "n/a", "artifacts": "qa reports"},
    {"id": 36, "name": "Configurable Models / Providers",
     "modules": ["config/defaults.py", "core/providers/registry.py"],
     "tools": ["services_status", "comm_status"],
     "entrypoints": ["cli --health"],
     "offline": "partial", "risk": "low", "dependency": "configured providers",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 37, "name": "Core Integration / Orchestration",
     "modules": ["core/integration.py"],
     "tools": ["dashboard", "health_rollup"],
     "entrypoints": ["cli --health", "cli --repl"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 38, "name": "GUI Desktop App",
     "modules": ["arven_gui.py", "arven_3d.py"], "tools": [],
     "entrypoints": ["app.py (FROZEN GUI)", "arven_gui.py (FROZEN)"],
     "offline": True, "risk": "low",
     "dependency": "Tk + pyglet (frozen surface; terminal equivalents live in counterpart features)",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 39, "name": "Advanced Browser Control",
     "modules": ["core/providers/browser_provider.py", "tools/browser.py"],
     "tools": ["browser_provider_status", "browser_bookmark_add",
               "browser_bookmark_list", "browser_bookmark_search",
               "browser_provider_search", "browser_status", "browser_navigate",
               "browser_search"],
     "entrypoints": ["cli --ask 'browser status'"],
     "offline": "partial", "risk": "medium", "dependency": "Playwright backend (optional)",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/browser_bookmarks.json"},
    {"id": 40, "name": "Advanced Vision",
     "modules": ["core/providers/vision_provider.py", "tools/vision_tools.py"],
     "tools": ["vision_metadata", "vision_analyze", "vision_coordinates",
               "image_analyze", "vision_status"],
     "entrypoints": ["cli --ask 'analyze image X'"],
     "offline": True, "risk": "low", "dependency": "PIL (local)",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 41, "name": "Image Generation",
     "modules": ["core/providers/media_gen.py"],
     "tools": ["image_generate"],
     "entrypoints": ["cli --ask 'generate an image'"],
     "offline": "partial", "risk": "medium",
     "dependency": "IMAGE_GENERATION_PROVIDER (else placeholder canvas only)",
     "persistence": False, "recovery": "n/a", "artifacts": "GeneratedImages/"},
    {"id": 42, "name": "Video Generation",
     "modules": ["core/providers/media_gen.py"],
     "tools": ["video_generate", "video_status", "video_cancel"],
     "entrypoints": ["cli --ask 'generate a video'"],
     "offline": "partial", "risk": "medium",
     "dependency": "VIDEO_GENERATION_PROVIDER (else storyboard only)",
     "persistence": True, "recovery": "job-based", "artifacts": "GeneratedVideos/"},
    {"id": 43, "name": "Android Control",
     "modules": ["core/providers/android_provider.py", "tools/android_tools.py"],
     "tools": ["android_provider_status", "android_devices", "android_shell",
               "android_command", "android_status"],
     "entrypoints": ["cli --ask 'android status'"],
     "offline": True, "risk": "high", "dependency": "adb (honest UNAVAILABLE if absent)",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 44, "name": "IoT Control",
     "modules": ["core/providers/iot_provider.py"],
     "tools": ["iot_provider_status", "iot_register", "iot_list", "iot_set_state", "iot_remove"],
     "entrypoints": ["cli --ask 'iot status'"],
     "offline": True, "risk": "medium", "dependency": "local device registry",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/kv_iot.json"},
    {"id": 45, "name": "Email / Calendar / Messaging Integration",
     "modules": ["core/providers/communication_provider.py", "tools/communication_tools.py"],
     "tools": ["calendar_create", "calendar_events", "email_draft", "email_search",
               "email_send", "messaging_send", "email_templates", "email_compose",
               "email_provider_draft", "email_provider_send", "message_draft",
               "message_send", "comm_status"],
     "entrypoints": ["cli --ask 'compose an email'", "cli --ask 'calendar events'"],
     "offline": "partial", "risk": "high", "dependency": "SMTP/calendar config (NOT_CONFIGURED honest)",
     "persistence": True, "recovery": "n/a", "artifacts": "data/comms_outbox.json"},
    {"id": 46, "name": "Camera Functionality",
     "modules": ["core/providers/camera_provider.py"],
     "tools": ["screen_capture", "camera_capture", "camera_permission_grant", "capture_screen"],
     "entrypoints": ["cli --ask 'capture screen'"],
"offline": True, "risk": "medium", "dependency": "camera hardware (permission-gated)",
      "persistence": True, "recovery": "n/a", "artifacts": "Screenshots/"},
    {"id": 47, "name": "Autonomous Coding & Build Agent",
     "modules": ["core/build_agent.py"],
     "tools": ["build_run", "build_validate", "build_git_check", "build_fetch_remote", "qa_pytest"],
     "entrypoints": ["cli --ask 'build the project'"],
     "offline": True, "risk": "medium", "dependency": "python toolchain",
     "persistence": False, "recovery": "pipeline timeouts", "artifacts": "build output"},
    {"id": 48, "name": "Speaker Recognition & Personal Identity Memory",
     "modules": ["core/speech.py"],
     "tools": ["speaker_enroll", "speaker_recognize", "speaker_list"],
     "entrypoints": ["cli --ask 'speaker list'"],
     "offline": True, "risk": "low", "dependency": "local FFT voiceprints",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/speakers.json"},
    {"id": 49, "name": "Speaker-Based Language Control / Adaptive Multilingual Communication",
     "modules": ["core/speech.py"],
     "tools": ["language_detect", "language_set"],
     "entrypoints": ["cli --ask 'detect language'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 50, "name": "Autonomous Goal Execution & Deep Research Missions",
     "modules": ["core/missions.py", "core/planner.py"],
     "tools": ["mission_create", "mission_start", "mission_status", "mission_steps",
               "mission_pause", "mission_resume", "mission_finish", "mission_cancel",
               "mission_archive"],
     "entrypoints": ["cli --mission ...", "cli --orchestrate 'goal'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "REQUIRES restart-resume", "artifacts": "mission reports"},
    {"id": 51, "name": "Continuous Context & Situational Awareness",
     "modules": ["core/context_engine.py", "core/terminal_engine.py"],
     "tools": ["context_event_push", "context_focus", "context_query", "context_summary"],
     "entrypoints": ["cli --ask 'context summary'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/runtime/context_engine.json"},
    {"id": 52, "name": "Self-Improvement & Experience Learning",
     "modules": ["core/experience.py"],
     "tools": ["experience_record", "experience_similar", "experience_lessons"],
     "entrypoints": ["cli --ask 'record lesson X'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/experience.json"},
    {"id": 53, "name": "Smart Decision Support",
     "modules": ["core/decisions.py"],
     "tools": ["decision_criteria_add", "decision_option_add", "decision_evaluate", "decision_pros_cons"],
     "entrypoints": ["cli --ask 'evaluate decision X'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/decisions.json"},
    {"id": 54, "name": "Personal Task & Mission Manager",
     "modules": ["core/missions.py", "core/organizer.py"],
     "tools": ["mission_create", "mission_start", "mission_status", "mission_steps",
               "mission_finish", "mission_cancel", "organizer_daily_plan"],
     "entrypoints": ["cli --ask 'create mission X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "restart-resume", "artifacts": "data/runtime/missions.json"},
    {"id": 55, "name": "Automatic Workflow Builder",
     "modules": ["core/workflows.py"],
     "tools": ["workflow_define", "workflow_run", "workflow_status", "workflow_templates", "workflow_abort"],
     "entrypoints": ["cli --ask 'define workflow X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/workflows.json"},
    {"id": 56, "name": "Skill Creation System",
     "modules": ["core/skill_builder.py"],
     "tools": ["skill_define", "skill_invoke", "skill_list", "skill_verify"],
     "entrypoints": ["cli --ask 'create skill X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "skills/"},
    {"id": 57, "name": "Anomaly & Change Detection",
     "modules": ["core/anomaly.py"],
     "tools": ["anomaly_ingest", "anomaly_detect", "anomaly_report", "anomaly_set_bounds"],
     "entrypoints": ["cli --ask 'detect anomalies'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 58, "name": "Smart Alert & Urgency System",
     "modules": ["core/alerts.py"],
     "tools": ["alert_create", "alert_list", "alert_ack", "alert_close", "alert_active"],
     "entrypoints": ["cli --ask 'alert list'"],
     "offline": True, "risk": "low", "dependency": "local (channel-honest)",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/alerts.json"},
    {"id": 59, "name": "Digital Organization Manager",
     "modules": ["core/organizer.py"],
     "tools": ["organizer_daily_plan", "organizer_events", "organizer_event_create",
               "organizer_conflicts", "organizer_reminders", "organizer_reminder_create",
               "organizer_digest", "organizer_weekly"],
     "entrypoints": ["cli --ask 'daily plan'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/organizer.json"},
    {"id": 60, "name": "Security Guardian",
     "modules": ["core/cyber_toolkit.py", "core/security_guardian.py"],
     "tools": ["cyber_scan", "cyber_discover", "cyber_explain", "cyber_audit",
               "cyber_scope_add", "cyber_scope_list", "cyber_scope_remove",
               "guardian_exfil_scan", "guardian_credential_scan", "guardian_url_safety"],
     "entrypoints": ["cli --ask 'scan localhost'"],
     "offline": True, "risk": "high", "dependency": "authorized scopes only",
     "persistence": True, "recovery": "n/a", "artifacts": "data/cyber.json"},
    {"id": 61, "name": "Automatic Backup & Recovery Manager",
     "modules": ["core/backup.py"],
     "tools": ["backup_snapshot", "backup_list", "backup_verify", "backup_restore",
               "backup_rotate", "backup_classify"],
     "entrypoints": ["cli --ask 'backup snapshot'"],
     "offline": True, "risk": "high", "dependency": "local FS",
     "persistence": True, "recovery": "gated restore", "artifacts": "Backups/"},
    {"id": 62, "name": "Autonomous Testing & QA Agent",
     "modules": ["core/qa_engine.py"],
     "tools": ["qa_syntax", "qa_imports", "qa_style", "qa_todos", "qa_pytest", "qa_report"],
     "entrypoints": ["cli --ask 'run tests'"],
     "offline": True, "risk": "medium", "dependency": "pytest (for qa_pytest)",
     "persistence": False, "recovery": "n/a", "artifacts": "qa reports"},
    {"id": 63, "name": "Self-Diagnostics & Self-Healing",
     "modules": ["core/diagnostics.py"],
     "tools": ["diagnostics_run", "diagnostics_report"],
     "entrypoints": ["cli --ask 'diagnostics run'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 64, "name": "Performance Optimizer",
     "modules": ["core/performance.py"],
     "tools": ["perf_report", "perf_hotspots", "perf_benchmark", "perf_fps"],
     "entrypoints": ["cli --ask 'performance report'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": False, "recovery": "n/a", "artifacts": "data/performance.json"},
    {"id": 65, "name": "Personal Knowledge Graph",
     "modules": ["core/knowledge_graph.py"],
     "tools": ["graph_node_add", "graph_edge_add", "graph_neighbors", "graph_path", "graph_summary"],
     "entrypoints": ["cli --ask 'graph summary'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed (non-destructive)", "artifacts": "data/knowledge_graph.json"},
    {"id": 66, "name": "Automatic Knowledge Assimilation",
     "modules": ["core/assimilation.py"],
     "tools": ["knowledge_ingest", "knowledge_triple", "knowledge_conflicts"],
     "entrypoints": ["cli --ask 'ingest knowledge X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/assimilation.json"},
    {"id": 67, "name": "Meeting & Conversation Intelligence",
     "modules": ["core/meetings.py"],
     "tools": ["meeting_create", "meeting_topic_add", "meeting_decision_add",
               "meeting_action_item_add", "meeting_capture", "meeting_minutes",
               "meeting_export", "meeting_participant_register", "meeting_participants"],
     "entrypoints": ["cli --ask 'meeting minutes'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/meetings.json"},
    {"id": 68, "name": "Multi-Person Conversation Manager",
     "modules": ["core/meetings.py"],
     "tools": ["conversation_turn", "conversation_state", "meeting_participant_register", "meeting_participants"],
     "entrypoints": ["cli --ask 'conversation state'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/meetings.json"},
    {"id": 69, "name": "Emotional & Conversational State Awareness",
     "modules": ["core/affect.py"],
     "tools": ["affect_observe", "affect_mood", "affect_tone"],
     "entrypoints": ["cli --ask 'affect status'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 70, "name": "Memory Importance & Forgetting System",
     "modules": ["core/memory_lifecycle.py"],
     "tools": ["memory_age", "memory_protect", "memory_forget_candidates", "memory_merge_suggest"],
     "entrypoints": ["cli --ask 'memory age'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "non-destructive", "artifacts": "n/a"},
    {"id": 71, "name": "Source & Fact Verification Engine",
     "modules": ["core/fact_check.py"],
     "tools": ["fact_check", "fact_cross_check"],
     "entrypoints": ["cli --ask 'fact check X'"],
     "offline": True, "risk": "low", "dependency": "local heuristics",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 72, "name": "Automatic Report & Presentation Builder",
     "modules": ["core/reports.py"],
     "tools": ["report_render", "report_section_add", "report_export"],
     "entrypoints": ["cli --ask 'render report'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "n/a", "artifacts": "reports/"},
    {"id": 73, "name": "Multi-Agent Collaboration",
     "modules": ["core/collaboration.py"],
     "tools": ["board_create", "board_card_add", "board_card_move", "board_mentions", "board_summary"],
     "entrypoints": ["cli --ask 'board summary'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/collab.json"},
    {"id": 74, "name": "Dynamic Planning & Replanning",
     "modules": ["core/planner.py", "core/plan_execution.py"],
     "tools": ["plan_create", "plan_status", "plan_list", "plan_replan", "plan_complete", "plan_deprecate"],
     "entrypoints": ["cli --ask 'create plan X'", "cli --repl"],
     "offline": True, "risk": "medium", "dependency": "local + registry",
     "persistence": True, "recovery": "replan/escalate", "artifacts": "data/planner.json"},
    {"id": 75, "name": "Human-in-the-Loop Escalation",
     "modules": ["core/escalation.py"],
     "tools": ["escalate", "escalation_handoff", "escalation_remind", "escalation_resolve"],
     "entrypoints": ["cli --ask 'escalate X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "n/a", "artifacts": "data/escalation.json"},
    {"id": 76, "name": "Simulation / What-If Engine",
     "modules": ["core/simulation.py"],
     "tools": ["simulation_run", "simulation_sensitivity", "simulation_report"],
     "entrypoints": ["cli --ask 'simulate X'"],
     "offline": True, "risk": "low", "dependency": "local deterministic models",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 77, "name": "Personal Digital Twin / Boss Model",
     "modules": ["core/boss_model.py"],
     "tools": ["boss_facts", "boss_consult", "boss_set_preference"],
     "entrypoints": ["cli --ask 'boss preferences'"],
     "offline": True, "risk": "low", "dependency": "consented facts only",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/boss_model.json"},
    {"id": 78, "name": "ARVEN Self-Architecture Manager",
     "modules": ["core/architecture.py"],
     "tools": ["arch_census", "arch_graph", "arch_contract_audit", "arch_growth"],
     "entrypoints": ["cli --ask 'architecture census'"],
     "offline": True, "risk": "low", "dependency": "local modules",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 79, "name": "Real-World Action Agent",
     "modules": ["core/providers/world_actions.py"],
     "tools": ["action_create", "action_dry_run", "action_execute", "action_status"],
     "entrypoints": ["cli --ask 'action status'"],
     "offline": True, "risk": "high", "dependency": "local rule/action store",
     "persistence": True, "recovery": "dry-run before execute", "artifacts": "n/a"},
    {"id": 80, "name": "Travel & Trip Autopilot",
     "modules": ["core/providers/travel_provider.py"],
     "tools": ["travel_plan", "travel_itinerary", "travel_book"],
     "entrypoints": ["cli --ask 'plan travel to X'"],
     "offline": True, "risk": "medium", "dependency": "local itinerary builder",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/kv_travel.json"},
    {"id": 81, "name": "Personal Finance Intelligence",
     "modules": ["core/providers/finance_provider.py", "core/undo.py"],
     "tools": ["finance_transaction_add", "finance_transaction_list",
               "finance_transaction_void", "finance_transaction_delete",
               "finance_budget_set", "finance_budget_status", "finance_report",
               "finance_investment_add", "finance_portfolio"],
     "entrypoints": ["cli --ask 'finance report'"],
     "offline": True, "risk": "high", "dependency": "local + undo",
     "persistence": True, "recovery": "undo/rollback", "artifacts": "data/finance.json"},
    {"id": 82, "name": "Home & Environment Intelligence",
     "modules": ["core/providers/home_provider.py"],
     "tools": ["home_status", "home_routines", "home_run_routine", "home_energy_estimate"],
     "entrypoints": ["cli --ask 'home status'"],
     "offline": True, "risk": "medium", "dependency": "local routines",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 83, "name": "Vehicle Intelligence",
     "modules": ["core/providers/vehicle_provider.py"],
     "tools": ["vehicle_status", "vehicle_maintenance_log", "vehicle_registration", "vehicle_reminders"],
     "entrypoints": ["cli --ask 'vehicle status'"],
     "offline": True, "risk": "medium", "dependency": "OBD NOT_CONFIGURED honest",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/kv_vehicle.json"},
    {"id": 84, "name": "Location-Aware Assistance",
     "modules": ["core/providers/location_provider.py"],
     "tools": ["location_status", "location_set", "location_get", "location_geocode", "distance"],
     "entrypoints": ["cli --ask 'location status'"],
     "offline": True, "risk": "low", "dependency": "manual location store",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/kv_location.json"},
    {"id": 85, "name": "Personal Shopping Agent",
     "modules": ["core/providers/shopping_provider.py"],
     "tools": ["shopping_list_create", "shopping_list_add", "shopping_price_memo",
               "shopping_compare", "shopping_purchase"],
     "entrypoints": ["cli --ask 'shopping list'"],
     "offline": True, "risk": "high", "dependency": "local list store",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/shopping.json"},
    {"id": 86, "name": "Life & Appointment Coordinator",
     "modules": ["core/organizer.py", "core/events.py"],
     "tools": ["organizer_event_create", "organizer_events", "organizer_conflicts",
               "event_add", "event_upcoming", "event_reminders"],
     "entrypoints": ["cli --ask 'add event X'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/organizer.json"},
    {"id": 87, "name": "Personal Learning Tutor",
     "modules": ["core/advisor.py"],
     "tools": ["tutor_curriculum", "tutor_assess", "tutor_next"],
     "entrypoints": ["cli --ask 'tutor curriculum'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/advisor_tutor.json"},
    {"id": 88, "name": "Career Autopilot",
     "modules": ["core/advisor.py"],
     "tools": ["career_gap", "career_interview_prep"],
     "entrypoints": ["cli --ask 'career gap'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/advisor_career.json"},
    {"id": 89, "name": "Relationship & Social Assistant",
     "modules": ["core/advisor.py"],
     "tools": ["relationship_checkin", "relationship_patterns"],
     "entrypoints": ["cli --ask 'relationship checkin'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/advisor_relationship.json"},
    {"id": 90, "name": "Communication Agent",
     "modules": ["core/advisor.py"],
     "tools": ["coach_draft", "coach_tone_check", "coach_speaking_tips",
               "interaction_plan", "interaction_followups"],
     "entrypoints": ["cli --ask 'coach draft'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/advisor_comm.json"},
    {"id": 91, "name": "Life Operating System",
     "modules": ["core/life_os.py"],
     "tools": ["life_checklist", "life_ritual_add", "life_satisfaction_track", "life_review"],
     "entrypoints": ["cli --ask 'life review'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "n/a"},
    {"id": 92, "name": "Real-Time Event Response",
     "modules": ["core/event_response.py", "core/events.py"],
     "tools": ["er_register", "er_ingest", "er_history", "er_stats", "er_unregister",
               "event_add", "event_upcoming", "event_reminders", "event_conflicts", "event_export"],
     "entrypoints": ["cli --ask 'event stats'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/event_response.json"},
    {"id": 93, "name": "Navigation & Physical-World Guidance",
     "modules": ["core/providers/navigation_provider.py"],
     "tools": ["route_plan", "route_eta"],
     "entrypoints": ["cli --ask 'route plan'"],
     "offline": True, "risk": "low", "dependency": "local route math",
     "persistence": False, "recovery": "n/a", "artifacts": "n/a"},
    {"id": 94, "name": "Physical Device / Robot Interface",
     "modules": ["core/robot.py"],
     "tools": ["robot_envelope", "robot_plan", "robot_collision", "robot_home",
               "robot_arm", "robot_disarm", "robot_execute", "robot_teach",
               "robot_replay", "robot_skills"],
     "entrypoints": ["cli --ask 'robot status'"],
     "offline": True, "risk": "high", "dependency": "safety envelope required",
     "persistence": True, "recovery": "safety fail-safe", "artifacts": "robot actions lib"},
    {"id": 95, "name": "Experiment & Engineering Agent",
     "modules": ["core/engineering.py"],
     "tools": ["eng_spec_create", "eng_sprint_board", "eng_task_add", "eng_measure_log", "eng_export"],
     "entrypoints": ["cli --ask 'create spec X'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "engineering docs"},
    {"id": 96, "name": "Project Supply-Chain Agent",
     "modules": ["core/supply_chain.py"],
     "tools": ["inventory_item_add", "inventory_receive", "inventory_issue",
               "inventory_adjust", "inventory_reorder", "inventory_status",
               "inventory_stock_value", "inventory_audit"],
     "entrypoints": ["cli --ask 'inventory status'"],
     "offline": True, "risk": "medium", "dependency": "user-entered inventory",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/inventory.json"},
    {"id": 97, "name": "Universal Service Orchestrator",
     "modules": ["core/services.py"],
     "tools": ["services_status", "services_register", "services_health",
               "services_start", "services_stop", "services_degraded"],
     "entrypoints": ["cli --ask 'services status'"],
     "offline": True, "risk": "high", "dependency": "local service registry",
     "persistence": True, "recovery": "health checks", "artifacts": "data/services.json"},
    {"id": 98, "name": "ARVEN Autonomous Command Center",
     "modules": ["core/command_center.py"],
     "tools": ["dashboard", "health_rollup", "set_flag"],
     "entrypoints": ["cli --health", "cli --ask 'dashboard'"],
     "offline": True, "risk": "low", "dependency": "local",
     "persistence": True, "recovery": "n/a", "artifacts": "data/command_center.json"},
    {"id": 99, "name": "Environment & World Understanding",
     "modules": ["core/world_state.py"],
     "tools": ["world_state_set", "world_state_update", "world_state_query",
               "world_state_project", "world_state_consistency"],
     "entrypoints": ["cli --ask 'world state query'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "versioned", "artifacts": "data/world_state.json"},
    {"id": 100, "name": "Knowledge & Skill Transfer Engine",
     "modules": ["core/assimilation.py", "core/experience.py"],
     "tools": ["knowledge_ingest", "knowledge_triple", "skill_invoke", "experience_lessons"],
     "entrypoints": ["cli --ask 'transfer knowledge X'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "skills/"},
    {"id": 101, "name": "ARVEN Continuity / Legacy System",
     "modules": ["core/continuity.py"],
     "tools": ["continuity_snapshot", "continuity_resume", "continuity_orphans"],
     "entrypoints": ["cli --ask 'continuity snapshot'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "snapshot/resume", "artifacts": "data/continuity.json"},
    {"id": 102, "name": "Universal Undo / Transaction Recovery",
     "modules": ["core/undo.py"],
     "tools": ["txn_begin", "txn_op", "txn_commit", "txn_rollback", "txn_status", "txn_active"],
     "entrypoints": ["cli --ask 'begin transaction'"],
     "offline": True, "risk": "medium", "dependency": "local kv",
     "persistence": True, "recovery": "rollback/undo", "artifacts": "data/undo.json"},
    {"id": 103, "name": "Versioned Project Memory",
     "modules": ["core/project_memory.py"],
     "tools": ["project_create", "project_checkin", "project_status", "project_risk_update"],
     "entrypoints": ["cli --ask 'project status'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "versioned", "artifacts": "data/project_memory.json"},
    {"id": 104, "name": "Long-Running Mission Persistence",
     "modules": ["core/continuity.py", "core/missions.py"],
     "tools": ["mission_create", "mission_start", "continuity_snapshot", "continuity_resume"],
     "entrypoints": ["cli --orchestrate 'long mission'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "snapshot/resume", "artifacts": "data/runtime/missions.json"},
    {"id": 105, "name": "Identity & Access Control",
     "modules": ["core/access.py"],
     "tools": ["access_grant", "access_check", "access_revoke", "access_report", "privacy_consent"],
     "entrypoints": ["cli --ask 'access report'"],
     "offline": True, "risk": "high", "dependency": "local",
     "persistence": True, "recovery": "audit", "artifacts": "data/access.json"},
    {"id": 106, "name": "Privacy, Recording & Adaptive Self-Learning",
     "modules": ["core/privacy.py"],
     "tools": ["privacy_inventory", "privacy_export", "privacy_erasure",
               "privacy_consent", "privacy_report", "guardian_credential_scan",
               "guardian_exfil_scan"],
     "entrypoints": ["cli --ask 'privacy report'"],
     "offline": True, "risk": "high", "dependency": "local",
     "persistence": True, "recovery": "n/a", "artifacts": "data/privacy.json"},
    {"id": 107, "name": "Real-Time Multimodal Interaction",
     "modules": ["core/multimodal.py"],
     "tools": ["multimodal_ingest", "multimodal_recent", "image_analyze", "vision_analyze"],
     "entrypoints": ["cli --ask 'ingest image'"],
     "offline": True, "risk": "medium", "dependency": "local",
     "persistence": True, "recovery": "kv-backed", "artifacts": "data/multimodal.json"},
    {"id": 108, "name": "Physical Robotics Safety Layer",
     "modules": ["core/robot.py"],
     "tools": ["robot_envelope", "robot_collision", "robot_disarm", "robot_home"],
     "entrypoints": ["cli --ask 'robot envelope'"],
     "offline": True, "risk": "high", "dependency": "SAFETY > AUTONOMY enforced",
     "persistence": True, "recovery": "fail-safe", "artifacts": "robot envelope log"},
    {"id": 109, "name": "Resource & Capability Awareness",
     "modules": ["core/capability_awareness.py"],
     "tools": ["capability_probe", "capability_profile", "capability_software",
               "capability_permissions", "capability_graph", "capability_dependencies",
               "capability_refresh"],
     "entrypoints": ["cli --capabilities", "cli --resources"],
     "offline": True, "risk": "low", "dependency": "local probes (stdlib)",
     "persistence": True, "recovery": "refresh + stale detection", "artifacts": "capability snapshot"},
    {"id": 110, "name": "Autonomous Engineering, Prototyping & Spatial Visualization",
     "modules": ["core/engineering_autonomy.py"],
     "tools": ["eng_analyze", "eng_calculate", "eng_bom", "eng_document",
               "eng_geometry", "eng_build_loop", "eng_report"],
     "entrypoints": ["cli --orchestrate 'engineering task'", "cli --ask 'eng analyze ...'"],
     "offline": True, "risk": "medium", "dependency": "local (stdlib; pytest for build loop)",
     "persistence": True, "recovery": "artifact + build reports", "artifacts": "Output/engineering/*"},
    {"id": 111, "name": "Advanced Autonomous Command & Mission Orchestration",
     "modules": ["core/mission_orchestrator.py"],
     "tools": ["orchestrate", "orchestrator_status", "orchestrator_plan",
               "orchestrator_resume", "orchestrator_cancel", "orchestrator_report",
               "orchestrator_capable"],
     "entrypoints": ["cli --orchestrate 'goal'", "cli --mission"],
     "offline": True, "risk": "high", "dependency": "planner + missions + registry + security",
     "persistence": True, "recovery": "resume/replan/escalate", "artifacts": "mission reports"},
    {"id": 112, "name": "Async Tool Execution Engine",
     "modules": ["core/async_tools_engine.py", "tools/async_tools.py"],
     "tools": ["async_engine", "async_submit", "async_status", "async_result",
               "async_cancel", "async_wait", "async_recover"],
     "entrypoints": ["cli --feature 112", "cli --test-feature 112"],
     "offline": True, "risk": "high", "dependency": "local (threading) + registry",
     "persistence": True, "recovery": "restart recovery (persisted jobs)",
     "artifacts": "data/async_tools.json"},
    {"id": 113, "name": "Mid-Turn Mission Steering",
     "modules": ["core/mission_steering.py", "core/missions.py",
                 "core/mission_orchestrator.py", "tools/steering_tools.py"],
     "tools": ["steer_mission", "steering_queue", "steering_status"],
     "entrypoints": ["cli --feature 113", "cli --orchestrate ... STEER ..."],
     "offline": True, "risk": "medium", "dependency": "missions + orchestrator",
     "persistence": True, "recovery": "steering log + resume",
     "artifacts": "data/mission_steering.json"},
    {"id": 114, "name": "Dynamic Reasoning Control",
     "modules": ["core/reasoning_control.py", "tools/reasoning_tools.py"],
     "tools": ["reasoning_estimate", "reasoning_set", "reasoning_status"],
     "entrypoints": ["cli --feature 114", "cli --providers"],
     "offline": True, "risk": "medium",
     "dependency": "local (provider capability detection; honest UNSUPPORTED cap)",
     "persistence": True, "recovery": "set/status reconcile",
     "artifacts": "data/reasoning_control.json"},
    {"id": 115, "name": "Professional Computer Use Engine",
     "modules": ["core/computer_use_engine.py", "tools/computer_use_tools.py"],
     "tools": ["computer_use_status", "computer_use_observe",
               "computer_use_act", "computer_use_verify",
               "computer_use_workflow"],
     "entrypoints": ["cli --feature 115"],
     "offline": True, "risk": "high",
     "dependency": "ctypes user32 + PIL; honest CAPABILITY_UNSUPPORTED",
     "persistence": False, "recovery": "OBSERVE->PLAN->ACT->VERIFY->RECOVER",
     "artifacts": "Output/screenshots"},
    {"id": 116, "name": "Advanced CAD & 3D Reconstruction",
     "modules": ["core/cad_3d.py", "tools/cad_tools.py"],
     "tools": ["cad_detect", "cad_make", "cad_inspect", "cad_validate",
               "cad_export", "cad_reconstruct"],
     "entrypoints": ["cli --feature 116"],
     "offline": True, "risk": "low",
     "dependency": "stdlib mesh; OpenSCAD/FreeCAD/Blender -> CAD_MISSING",
     "persistence": True, "recovery": "validate/export read-back",
     "artifacts": "Output/cad/*"},
    {"id": 117, "name": "PCB Design & EDA Automation",
     "modules": ["core/pcb_eda.py", "tools/pcb_tools.py"],
     "tools": ["pcb_status", "pcb_board", "pcb_drc", "pcb_export",
               "pcb_fabrication_check"],
     "entrypoints": ["cli --feature 117"],
     "offline": True, "risk": "medium",
     "dependency": "stdlib (KiCad -> EDA_MISSING honest)",
     "persistence": True, "recovery": "DRC/export read-back",
     "artifacts": "Output/pcb/*"},
    {"id": 118, "name": "Autonomous Web/App/Game Creation & QA",
     "modules": ["core/web_app_engine.py", "tools/webapp_tools.py"],
     "tools": ["webapp_status", "webapp_create", "webapp_build",
               "webapp_inspect", "webapp_qa"],
     "entrypoints": ["cli --feature 118"],
     "offline": True, "risk": "high",
     "dependency": "python stdlib + pytest for QA loop",
     "persistence": True, "recovery": "failure -> fix -> rebuild -> retest",
     "artifacts": "Output/webapps/*"},
    {"id": 119, "name": "Scientific Software & Computational Workflow Engine",
     "modules": ["core/scientific.py", "tools/scientific_tools.py"],
     "tools": ["sci_detect", "sci_compute", "sci_validate", "sci_analyze",
               "sci_workflow", "sci_report", "sci_methods"],
     "entrypoints": ["cli --feature 119"],
     "offline": True, "risk": "low",
     "dependency": "numpy/scipy/pandas/matplotlib/sympy -> DEPENDENCY_MISSING honest; stdlib always",
     "persistence": True, "recovery": "validate analytic-vs-numeric",
     "artifacts": "Output/scientific/*, data/scientific_engine.json"},
    {"id": 120, "name": "Template-Aware Professional Artifact Engine",
     "modules": ["core/artifact_engine.py", "tools/artifact_tools.py"],
     "tools": ["art_status", "art_inspect", "art_generate", "art_validate",
               "art_ensure"],
     "entrypoints": ["cli --feature 120"],
     "offline": True, "risk": "medium",
     "dependency": "docx/openpyxl/reportlab optional; zero-dep writers",
     "persistence": True, "recovery": "LOAD->INSPECT->GENERATE->VALIDATE->COMPARE->FINALIZE",
     "artifacts": "Output/artifacts/*"},
    {"id": 121, "name": "Native MCP Integration Layer",
     "modules": ["core/mcp_layer.py", "core/_mcp_echo_server.py",
                 "tools/mcp_tools.py"],
     "tools": ["mcp_status", "mcp_discover", "mcp_connect", "mcp_authorize",
               "mcp_call", "mcp_register"],
     "entrypoints": ["cli --feature 121"],
     "offline": True, "risk": "high",
     "dependency": "real JSON-RPC stdio client; allowlist + confirmation",
     "persistence": True, "recovery": "DISCOVER->AUTHORIZE->REGISTER->GUARDED CALL (denial proven)",
     "artifacts": "data/mcp_layer.json"},
    {"id": 122, "name": "Extreme Long-Context Intelligence Engine",
     "modules": ["core/long_context.py", "tools/context_tools.py"],
     "tools": ["ctx_detect", "ctx_budget", "ctx_process", "ctx_document",
               "ctx_checkpoint", "ctx_restore"],
     "entrypoints": ["cli --feature 122"],
     "offline": True, "risk": "low",
     "dependency": "stdlib; provider-aware window (honest, no 1M claim)",
     "persistence": True, "recovery": "RETRIEVE->COMPRESS->COMPACT->CONTINUE; checkpoint/restore",
     "artifacts": "Output/long_context/*, data/long_context.json"},
    {"id": 123, "name": "Mechatronics Co-Design & Hardware-in-the-Loop Engine",
     "modules": ["core/mechatronics.py", "tools/mechatronics_tools.py"],
     "tools": ["mechatronics_create_system", "mechatronics_validate",
               "mechatronics_simulate", "mechatronics_discover",
               "mechatronics_connect", "mechatronics_disconnect",
               "mechatronics_read", "mechatronics_write", "mechatronics_hil",
               "mechatronics_diagnostics", "mechatronics_bom",
               "mechatronics_interfaces"],
     "entrypoints": ["cli --feature 123"],
     "offline": True, "risk": "high",
     "dependency": "stdlib (serial optional); hardware presence is real-only, "
                   "mock clearly SIMULATED_DEVICE",
     "persistence": True, "recovery": "digital twin CREATE/SAVE/LOAD/REVALIDATE",
     "artifacts": "Output/mechatronics/*, data/mechatronics.json"},
]


_FEATURE_IDS = [f["id"] for f in FEATURES]


def list_features():
    return list(FEATURES)


def feature(feature_id):
    fid = int(feature_id)
    for entry in FEATURES:
        if entry["id"] == fid:
            return entry
    return None


def feature_tools(feature_id):
    entry = feature(feature_id)
    return list(entry["tools"]) if entry else []


def is_framework_feature(feature_id):
    entry = feature(feature_id)
    return bool(entry) and not entry["tools"]


def feature_ids():
    return list(_FEATURE_IDS)


def catalog_summary():
    with_tools = sum(1 for f in FEATURES if f["tools"])
    frameworks = len(FEATURES) - with_tools
    return {
        "total": len(FEATURES),
        "with_tools": with_tools,
        "framework": frameworks,
        "offline_full": sum(1 for f in FEATURES if f["offline"] is True),
        "offline_partial": sum(1 for f in FEATURES if f["offline"] == "partial"),
        "offline_network": sum(1 for f in FEATURES if f["offline"] is False),
    }


__all__ = [
    "FEATURES", "list_features", "feature", "feature_tools",
    "is_framework_feature", "feature_ids", "catalog_summary",
]